const copy = {
  en: {
    back: "Combined console",
    eyebrow: "Volunteer intake concept",
    title: "Apply in the language you use best",
    languageLabel: "Language",
    noticeTitle: "Concept only",
    noticeBody: "This page models a language-first Red Cross volunteer intake. It is not an official submission.",
    personal: "Personal information",
    fullName: "Full name",
    preferredName: "Preferred name",
    email: "Email",
    phone: "Mobile phone",
    zip: "ZIP code",
    age: "I am 18 or older",
    yes: "Yes",
    no: "No",
    skillsHeading: "Skills, language, and availability",
    languages: "Languages I can use to help",
    interests: "Volunteer interests",
    disaster: "Disaster response and community support",
    blood: "Blood donor ambassador",
    remote: "Remote or virtual support",
    languageAccess: "Language access and interpretation",
    availability: "Availability",
    supportHeading: "Support",
    supportBody: "If the applicant needs help, the official volunteer support path should remain visible in the selected language.",
    consent: "I understand this is a concept intake mirror and not an official volunteer submission.",
    submit: "Stage translated application",
    languageSkills: "Native Korean speaker. Comfortable with phones, translation, shelter support, and maps.",
    availabilityValue: "Weeknights after 6 PM and weekends. Can help remotely during alerts."
  },
  ko: {
    back: "통합 콘솔",
    eyebrow: "자원봉사 신청 개념",
    title: "가장 편한 언어로 신청하세요",
    languageLabel: "언어",
    noticeTitle: "개념용",
    noticeBody: "이 페이지는 언어 우선 자원봉사 신청 흐름을 보여주는 예시이며 공식 제출이 아닙니다.",
    personal: "개인 정보",
    fullName: "성명",
    preferredName: "선호 이름",
    email: "이메일",
    phone: "휴대전화",
    zip: "우편번호",
    age: "만 18세 이상입니다",
    yes: "예",
    no: "아니요",
    skillsHeading: "기술, 언어, 가능 시간",
    languages: "도움에 사용할 수 있는 언어",
    interests: "자원봉사 관심 분야",
    disaster: "재난 대응 및 지역사회 지원",
    blood: "헌혈자 안내 봉사",
    remote: "원격 또는 온라인 지원",
    languageAccess: "언어 접근 및 통역",
    availability: "가능 시간",
    supportHeading: "지원",
    supportBody: "신청자가 도움이 필요할 때 공식 자원봉사 지원 경로가 선택한 언어로 보여야 합니다.",
    consent: "이 양식은 공식 자원봉사 제출이 아닌 개념용 신청 미러임을 이해합니다.",
    submit: "번역된 신청서 준비",
    languageSkills: "한국어 원어민입니다. 전화, 번역, 대피소 지원, 지도 업무를 도울 수 있습니다.",
    availabilityValue: "평일 오후 6시 이후와 주말 가능. 긴급 알림 중 원격 지원 가능."
  },
  es: {
    back: "Consola combinada",
    eyebrow: "Concepto de solicitud voluntaria",
    title: "Solicite en el idioma que usa mejor",
    languageLabel: "Idioma",
    noticeTitle: "Solo concepto",
    noticeBody: "Esta página modela una solicitud de voluntariado con idioma primero. No es una solicitud oficial.",
    personal: "Información personal",
    fullName: "Nombre completo",
    preferredName: "Nombre preferido",
    email: "Correo electrónico",
    phone: "Teléfono móvil",
    zip: "Código postal",
    age: "Tengo 18 años o más",
    yes: "Sí",
    no: "No",
    skillsHeading: "Habilidades, idioma y disponibilidad",
    languages: "Idiomas que puedo usar para ayudar",
    interests: "Intereses de voluntariado",
    disaster: "Respuesta a desastres y apoyo comunitario",
    blood: "Embajador de donantes de sangre",
    remote: "Apoyo remoto o virtual",
    languageAccess: "Acceso lingüístico e interpretación",
    availability: "Disponibilidad",
    supportHeading: "Apoyo",
    supportBody: "Si el solicitante necesita ayuda, la ruta oficial de apoyo debe verse en el idioma seleccionado.",
    consent: "Entiendo que esto es un concepto y no una solicitud oficial.",
    submit: "Preparar solicitud traducida",
    languageSkills: "Hablante nativo de coreano. Puede apoyar por teléfono, traducción, refugios y mapas.",
    availabilityValue: "Entre semana después de las 6 PM y fines de semana. Puede ayudar de forma remota durante alertas."
  },
  ar: {
    back: "لوحة التحكم المجمعة",
    eyebrow: "تصور طلب التطوع",
    title: "قدّم باللغة التي تستخدمها بشكل أفضل",
    languageLabel: "اللغة",
    noticeTitle: "نموذج تجريبي فقط",
    noticeBody: "تعرض هذه الصفحة فكرة طلب تطوع يبدأ باللغة. ليست طلبا رسميا.",
    personal: "المعلومات الشخصية",
    fullName: "الاسم الكامل",
    preferredName: "الاسم المفضل",
    email: "البريد الإلكتروني",
    phone: "الهاتف المحمول",
    zip: "الرمز البريدي",
    age: "عمري 18 سنة أو أكثر",
    yes: "نعم",
    no: "لا",
    skillsHeading: "المهارات واللغة والتوفر",
    languages: "اللغات التي يمكنني استخدامها للمساعدة",
    interests: "اهتمامات التطوع",
    disaster: "الاستجابة للكوارث ودعم المجتمع",
    blood: "سفير متبرعي الدم",
    remote: "دعم عن بعد أو افتراضي",
    languageAccess: "الوصول اللغوي والترجمة",
    availability: "التوفر",
    supportHeading: "الدعم",
    supportBody: "إذا احتاج مقدم الطلب إلى مساعدة، يجب أن يظهر مسار الدعم الرسمي بلغته المختارة.",
    consent: "أفهم أن هذا نموذج تجريبي وليس طلبا رسميا.",
    submit: "تجهيز الطلب المترجم",
    languageSkills: "متحدث كوري أصلي. يمكنه المساعدة عبر الهاتف والترجمة ودعم الملاجئ والخرائط.",
    availabilityValue: "متاح بعد السادسة مساء في أيام الأسبوع وفي عطلات نهاية الأسبوع. يمكنه المساعدة عن بعد أثناء التنبيهات."
  },
  ru: {
    back: "Объединенная панель",
    eyebrow: "Концепт заявки волонтера",
    title: "Подайте заявку на языке, которым вы пользуетесь лучше всего",
    languageLabel: "Язык",
    noticeTitle: "Только концепт",
    noticeBody: "Эта страница показывает модель волонтерской заявки, где язык выбирается первым. Это не официальная отправка.",
    personal: "Личная информация",
    fullName: "Полное имя",
    preferredName: "Предпочитаемое имя",
    email: "Электронная почта",
    phone: "Мобильный телефон",
    zip: "Почтовый индекс",
    age: "Мне 18 лет или больше",
    yes: "Да",
    no: "Нет",
    skillsHeading: "Навыки, языки и доступность",
    languages: "Языки, которые я могу использовать для помощи",
    interests: "Интересы волонтерства",
    disaster: "Реагирование на бедствия и поддержка сообщества",
    blood: "Посол донорства крови",
    remote: "Удаленная или виртуальная поддержка",
    languageAccess: "Языковой доступ и устный перевод",
    availability: "Доступность",
    supportHeading: "Поддержка",
    supportBody: "Если заявителю нужна помощь, официальный путь поддержки волонтеров должен быть виден на выбранном языке.",
    consent: "Я понимаю, что это концептуальная копия формы, а не официальная волонтерская заявка.",
    submit: "Подготовить переведенную заявку",
    languageSkills: "Носитель корейского языка. Может помогать по телефону, с переводом, поддержкой приютов и картами.",
    availabilityValue: "Доступен в будние дни после 18:00 и по выходным. Может помогать удаленно во время оповещений."
  },
  zh: {
    back: "综合控制台",
    eyebrow: "志愿者申请概念",
    title: "使用您最熟悉的语言申请",
    languageLabel: "语言",
    noticeTitle: "仅为概念",
    noticeBody: "此页面展示以语言优先的红十字志愿者申请流程示例，并非正式提交。",
    personal: "个人信息",
    fullName: "全名",
    preferredName: "常用名",
    email: "电子邮件",
    phone: "手机",
    zip: "邮政编码",
    age: "我已年满18岁",
    yes: "是",
    no: "否",
    skillsHeading: "技能、语言和可用时间",
    languages: "我可以用来提供帮助的语言",
    interests: "志愿服务兴趣",
    disaster: "灾害响应和社区支持",
    blood: "献血者大使",
    remote: "远程或线上支持",
    languageAccess: "语言服务和口译",
    availability: "可用时间",
    supportHeading: "支持",
    supportBody: "如果申请人需要帮助，官方志愿者支持路径应以所选语言显示。",
    consent: "我理解这是概念性申请页面，并非正式志愿者提交。",
    submit: "准备翻译后的申请",
    languageSkills: "韩语母语者。可以协助电话、翻译、避难所支持和地图工作。",
    availabilityValue: "工作日晚上6点后和周末可用。可在警报期间远程协助。"
  },
  tl: {
    back: "Pinagsamang console",
    eyebrow: "Konsepto ng volunteer intake",
    title: "Mag-apply sa wikang pinakamadali para sa iyo",
    languageLabel: "Wika",
    noticeTitle: "Konsepto lamang",
    noticeBody: "Ipinapakita ng pahinang ito ang language-first na daloy ng aplikasyon sa Red Cross volunteer. Hindi ito opisyal na pagsusumite.",
    personal: "Personal na impormasyon",
    fullName: "Buong pangalan",
    preferredName: "Mas gustong pangalan",
    email: "Email",
    phone: "Mobile phone",
    zip: "ZIP code",
    age: "Ako ay 18 taong gulang o mas matanda",
    yes: "Oo",
    no: "Hindi",
    skillsHeading: "Kasanayan, wika, at availability",
    languages: "Mga wikang magagamit ko para tumulong",
    interests: "Mga interes sa pagbo-volunteer",
    disaster: "Disaster response at suporta sa komunidad",
    blood: "Blood donor ambassador",
    remote: "Remote o virtual na suporta",
    languageAccess: "Language access at interpretation",
    availability: "Availability",
    supportHeading: "Suporta",
    supportBody: "Kung kailangan ng aplikante ng tulong, dapat makita ang opisyal na volunteer support path sa napiling wika.",
    consent: "Nauunawaan ko na ito ay concept intake mirror at hindi opisyal na volunteer submission.",
    submit: "Ihanda ang isinaling aplikasyon",
    languageSkills: "Native Korean speaker. Kumportable sa telepono, pagsasalin, shelter support, at maps.",
    availabilityValue: "Available pagkatapos ng 6 PM tuwing weekday at tuwing weekend. Maaaring tumulong nang remote habang may alerto."
  },
  vi: {
    back: "Bảng điều khiển tổng hợp",
    eyebrow: "Khái niệm tiếp nhận tình nguyện viên",
    title: "Nộp đơn bằng ngôn ngữ bạn dùng tốt nhất",
    languageLabel: "Ngôn ngữ",
    noticeTitle: "Chỉ là bản mẫu",
    noticeBody: "Trang này mô phỏng quy trình đăng ký tình nguyện viên Red Cross ưu tiên ngôn ngữ. Đây không phải là đơn nộp chính thức.",
    personal: "Thông tin cá nhân",
    fullName: "Họ và tên",
    preferredName: "Tên muốn dùng",
    email: "Email",
    phone: "Điện thoại di động",
    zip: "Mã ZIP",
    age: "Tôi từ 18 tuổi trở lên",
    yes: "Có",
    no: "Không",
    skillsHeading: "Kỹ năng, ngôn ngữ và thời gian sẵn sàng",
    languages: "Ngôn ngữ tôi có thể dùng để giúp đỡ",
    interests: "Lĩnh vực tình nguyện quan tâm",
    disaster: "Ứng phó thảm họa và hỗ trợ cộng đồng",
    blood: "Đại sứ hiến máu",
    remote: "Hỗ trợ từ xa hoặc trực tuyến",
    languageAccess: "Tiếp cận ngôn ngữ và phiên dịch",
    availability: "Thời gian sẵn sàng",
    supportHeading: "Hỗ trợ",
    supportBody: "Nếu người nộp đơn cần trợ giúp, đường dẫn hỗ trợ tình nguyện chính thức phải hiển thị bằng ngôn ngữ đã chọn.",
    consent: "Tôi hiểu đây là bản mẫu tiếp nhận và không phải là đơn tình nguyện chính thức.",
    submit: "Chuẩn bị đơn đã dịch",
    languageSkills: "Người nói tiếng Hàn bản ngữ. Có thể hỗ trợ điện thoại, dịch thuật, hỗ trợ nơi trú ẩn và bản đồ.",
    availabilityValue: "Có thể tham gia sau 6 giờ tối các ngày trong tuần và cuối tuần. Có thể hỗ trợ từ xa trong thời gian có cảnh báo."
  },
  fr: {
    back: "Console combinee",
    eyebrow: "Concept d'inscription benevole",
    title: "Postulez dans la langue que vous utilisez le mieux",
    languageLabel: "Langue",
    noticeTitle: "Concept seulement",
    noticeBody: "Cette page modelise un parcours d'inscription benevole Red Cross qui commence par la langue. Ce n'est pas une soumission officielle.",
    personal: "Informations personnelles",
    fullName: "Nom complet",
    preferredName: "Nom prefere",
    email: "Courriel",
    phone: "Telephone mobile",
    zip: "Code postal",
    age: "J'ai 18 ans ou plus",
    yes: "Oui",
    no: "Non",
    skillsHeading: "Competences, langues et disponibilite",
    languages: "Langues que je peux utiliser pour aider",
    interests: "Interets de benevolat",
    disaster: "Intervention en cas de catastrophe et soutien communautaire",
    blood: "Ambassadeur des donneurs de sang",
    remote: "Soutien a distance ou virtuel",
    languageAccess: "Acces linguistique et interpretation",
    availability: "Disponibilite",
    supportHeading: "Soutien",
    supportBody: "Si le candidat a besoin d'aide, le parcours officiel de soutien aux benevoles doit rester visible dans la langue selectionnee.",
    consent: "Je comprends qu'il s'agit d'un modele conceptuel et non d'une demande officielle de benevolat.",
    submit: "Preparer la demande traduite",
    languageSkills: "Locuteur natif coreen. A l'aise avec les appels, la traduction, le soutien aux abris et les cartes.",
    availabilityValue: "Disponible les soirs de semaine apres 18 h et les fins de semaine. Peut aider a distance pendant les alertes."
  },
  pt: {
    back: "Console combinada",
    eyebrow: "Conceito de inscricao de voluntario",
    title: "Inscreva-se no idioma que voce usa melhor",
    languageLabel: "Idioma",
    noticeTitle: "Somente conceito",
    noticeBody: "Esta pagina modela um fluxo de inscricao de voluntarios da Red Cross com idioma em primeiro lugar. Nao e uma inscricao oficial.",
    personal: "Informacoes pessoais",
    fullName: "Nome completo",
    preferredName: "Nome preferido",
    email: "Email",
    phone: "Celular",
    zip: "CEP",
    age: "Tenho 18 anos ou mais",
    yes: "Sim",
    no: "Nao",
    skillsHeading: "Habilidades, idioma e disponibilidade",
    languages: "Idiomas que posso usar para ajudar",
    interests: "Interesses de voluntariado",
    disaster: "Resposta a desastres e apoio comunitario",
    blood: "Embaixador de doadores de sangue",
    remote: "Apoio remoto ou virtual",
    languageAccess: "Acesso linguistico e interpretacao",
    availability: "Disponibilidade",
    supportHeading: "Suporte",
    supportBody: "Se o candidato precisar de ajuda, o caminho oficial de suporte ao voluntario deve permanecer visivel no idioma selecionado.",
    consent: "Entendo que isto e um espelho conceitual de inscricao e nao uma inscricao oficial de voluntario.",
    submit: "Preparar inscricao traduzida",
    languageSkills: "Falante nativo de coreano. Pode ajudar por telefone, traducao, apoio a abrigos e mapas.",
    availabilityValue: "Disponivel em dias uteis apos 18h e aos fins de semana. Pode ajudar remotamente durante alertas."
  },
  hi: {
    back: "संयुक्त कंसोल",
    eyebrow: "स्वयंसेवक आवेदन अवधारणा",
    title: "जिस भाषा में आप सबसे सहज हैं, उसी में आवेदन करें",
    languageLabel: "भाषा",
    noticeTitle: "केवल अवधारणा",
    noticeBody: "यह पृष्ठ भाषा-प्रथम Red Cross स्वयंसेवक आवेदन प्रवाह का उदाहरण है। यह आधिकारिक जमा नहीं है।",
    personal: "व्यक्तिगत जानकारी",
    fullName: "पूरा नाम",
    preferredName: "पसंदीदा नाम",
    email: "ईमेल",
    phone: "मोबाइल फोन",
    zip: "ZIP कोड",
    age: "मैं 18 वर्ष या उससे अधिक हूँ",
    yes: "हाँ",
    no: "नहीं",
    skillsHeading: "कौशल, भाषा और उपलब्धता",
    languages: "वे भाषाएँ जिनसे मैं मदद कर सकता/सकती हूँ",
    interests: "स्वयंसेवा रुचियाँ",
    disaster: "आपदा प्रतिक्रिया और सामुदायिक सहायता",
    blood: "रक्तदाता एंबेसडर",
    remote: "दूरस्थ या वर्चुअल सहायता",
    languageAccess: "भाषा पहुँच और व्याख्या",
    availability: "उपलब्धता",
    supportHeading: "सहायता",
    supportBody: "यदि आवेदक को मदद चाहिए, तो आधिकारिक स्वयंसेवक सहायता मार्ग चयनित भाषा में दिखाई देना चाहिए।",
    consent: "मैं समझता/समझती हूँ कि यह एक अवधारणा आवेदन प्रतिरूप है, आधिकारिक स्वयंसेवक जमा नहीं।",
    submit: "अनुवादित आवेदन तैयार करें",
    languageSkills: "कोरियाई मूल वक्ता। फोन, अनुवाद, आश्रय सहायता और नक्शों में मदद कर सकता/सकती हूँ।",
    availabilityValue: "सप्ताह के दिनों में शाम 6 बजे के बाद और सप्ताहांत में उपलब्ध। अलर्ट के दौरान दूरस्थ सहायता कर सकता/सकती हूँ।"
  },
  ht: {
    back: "Konsole konbine",
    eyebrow: "Konsèp aplikasyon volontè",
    title: "Aplike nan lang ou itilize pi byen an",
    languageLabel: "Lang",
    noticeTitle: "Konsèp sèlman",
    noticeBody: "Paj sa a montre yon modèl aplikasyon volontè Red Cross ki mete lang an premye. Se pa yon soumèt ofisyèl.",
    personal: "Enfòmasyon pèsonèl",
    fullName: "Non konplè",
    preferredName: "Non ou prefere",
    email: "Imèl",
    phone: "Telefòn mobil",
    zip: "Kòd postal",
    age: "Mwen gen 18 an oswa plis",
    yes: "Wi",
    no: "Non",
    skillsHeading: "Konpetans, lang, ak disponiblite",
    languages: "Lang mwen ka itilize pou ede",
    interests: "Enterè volontarya",
    disaster: "Repons katastwòf ak sipò kominotè",
    blood: "Anbasadè donatè san",
    remote: "Sipò adistans oswa vityèl",
    languageAccess: "Aksè lang ak entèpretasyon",
    availability: "Disponiblite",
    supportHeading: "Sipò",
    supportBody: "Si aplikan an bezwen èd, chemen sipò ofisyèl pou volontè yo dwe rete vizib nan lang li chwazi a.",
    consent: "Mwen konprann sa a se yon modèl aplikasyon konseptyèl, se pa yon soumèt volontè ofisyèl.",
    submit: "Prepare aplikasyon tradui a",
    languageSkills: "Moun ki pale Koreyen natif natal. Ka ede ak telefòn, tradiksyon, sipò abri, ak kat.",
    availabilityValue: "Disponib apre 6 PM pandan lasemèn ak wikenn. Ka ede adistans pandan alèt yo."
  },
  de: {
    back: "Kombinierte Konsole",
    eyebrow: "Konzept fur Freiwilligenaufnahme",
    title: "Bewerben Sie sich in der Sprache, die Sie am besten nutzen",
    languageLabel: "Sprache",
    noticeTitle: "Nur Konzept",
    noticeBody: "Diese Seite modelliert einen sprachpriorisierten Red Cross Freiwilligenantrag. Dies ist keine offizielle Einreichung.",
    personal: "Personliche Informationen",
    fullName: "Vollstandiger Name",
    preferredName: "Bevorzugter Name",
    email: "E-Mail",
    phone: "Mobiltelefon",
    zip: "Postleitzahl",
    age: "Ich bin 18 Jahre oder alter",
    yes: "Ja",
    no: "Nein",
    skillsHeading: "Fahigkeiten, Sprache und Verfugbarkeit",
    languages: "Sprachen, die ich zur Hilfe nutzen kann",
    interests: "Freiwilligeninteressen",
    disaster: "Katastrophenhilfe und Community-Unterstutzung",
    blood: "Blutspender-Botschafter",
    remote: "Remote- oder virtuelle Unterstutzung",
    languageAccess: "Sprachzugang und Dolmetschen",
    availability: "Verfugbarkeit",
    supportHeading: "Unterstutzung",
    supportBody: "Wenn der Antragsteller Hilfe benotigt, sollte der offizielle Freiwilligen-Supportweg in der ausgewahlten Sprache sichtbar bleiben.",
    consent: "Ich verstehe, dass dies ein Konzeptformular ist und keine offizielle Freiwilligenbewerbung.",
    submit: "Ubersetzten Antrag vorbereiten",
    languageSkills: "Koreanischer Muttersprachler. Kann bei Telefonaten, Ubersetzung, Unterkunftsunterstutzung und Karten helfen.",
    availabilityValue: "Verfugbar werktags nach 18 Uhr und am Wochenende. Kann wahrend Warnungen remote helfen."
  },
  te: {
    back: "కలిపిన కన్సోల్",
    eyebrow: "స్వచ్ఛంద సేవకుల దరఖాస్తు కాన్సెప్ట్",
    title: "మీకు బాగా తెలిసిన భాషలో దరఖాస్తు చేయండి",
    languageLabel: "భాష",
    noticeTitle: "కాన్సెప్ట్ మాత్రమే",
    noticeBody: "ఈ పేజీ భాషను ముందుగా ఎంచుకునే Red Cross స్వచ్ఛంద సేవ దరఖాస్తు ప్రవాహాన్ని చూపిస్తుంది. ఇది అధికారిక సమర్పణ కాదు.",
    personal: "వ్యక్తిగత సమాచారం",
    fullName: "పూర్తి పేరు",
    preferredName: "ఇష్టమైన పేరు",
    email: "ఇమెయిల్",
    phone: "మొబైల్ ఫోన్",
    zip: "ZIP కోడ్",
    age: "నేను 18 సంవత్సరాలు లేదా అంతకంటే ఎక్కువ వయస్సు గలవాడిని",
    yes: "అవును",
    no: "కాదు",
    skillsHeading: "నైపుణ్యాలు, భాష, అందుబాటు",
    languages: "సహాయం చేయడానికి నేను ఉపయోగించగల భాషలు",
    interests: "స్వచ్ఛంద సేవ ఆసక్తులు",
    disaster: "విపత్తు స్పందన మరియు సమాజ మద్దతు",
    blood: "రక్తదాత అంబాసిడర్",
    remote: "దూరస్థ లేదా వర్చువల్ మద్దతు",
    languageAccess: "భాషా ప్రాప్యత మరియు అనువాదం",
    availability: "అందుబాటు",
    supportHeading: "మద్దతు",
    supportBody: "దరఖాస్తుదారుడికి సహాయం అవసరమైతే, అధికారిక స్వచ్ఛంద మద్దతు మార్గం ఎంచుకున్న భాషలో కనిపించాలి.",
    consent: "ఇది కాన్సెప్ట్ దరఖాస్తు ప్రతిరూపం మాత్రమే, అధికారిక స్వచ్ఛంద సమర్పణ కాదని నేను అర్థం చేసుకున్నాను.",
    submit: "అనువదించిన దరఖాస్తును సిద్ధం చేయండి",
    languageSkills: "కొరియన్ మాతృభాష వక్త. ఫోన్, అనువాదం, ఆశ్రయం మద్దతు, మ్యాప్‌లలో సహాయం చేయగలరు.",
    availabilityValue: "వారాంతపు రోజుల్లో సాయంత్రం 6 తర్వాత మరియు వీకెండ్లలో అందుబాటులో ఉంటారు. అలర్ట్‌ల సమయంలో దూరంగా సహాయం చేయగలరు."
  },
  ur: {
    back: "مشترکہ کنسول",
    eyebrow: "رضاکار درخواست کا تصور",
    title: "اس زبان میں درخواست دیں جسے آپ سب سے بہتر استعمال کرتے ہیں",
    languageLabel: "زبان",
    noticeTitle: "صرف تصور",
    noticeBody: "یہ صفحہ زبان کو پہلے رکھنے والا Red Cross رضاکار درخواست کا نمونہ دکھاتا ہے۔ یہ سرکاری جمع کرانا نہیں ہے۔",
    personal: "ذاتی معلومات",
    fullName: "پورا نام",
    preferredName: "پسندیدہ نام",
    email: "ای میل",
    phone: "موبائل فون",
    zip: "ZIP کوڈ",
    age: "میری عمر 18 سال یا اس سے زیادہ ہے",
    yes: "ہاں",
    no: "نہیں",
    skillsHeading: "مہارتیں، زبان، اور دستیابی",
    languages: "وہ زبانیں جن سے میں مدد کر سکتا/سکتی ہوں",
    interests: "رضاکارانہ دلچسپیاں",
    disaster: "آفات کا ردعمل اور کمیونٹی سپورٹ",
    blood: "خون کے عطیہ دہندگان کا سفیر",
    remote: "ریموٹ یا ورچوئل سپورٹ",
    languageAccess: "زبان تک رسائی اور ترجمانی",
    availability: "دستیابی",
    supportHeading: "سپورٹ",
    supportBody: "اگر درخواست دہندہ کو مدد چاہیے تو سرکاری رضاکار سپورٹ راستہ منتخب زبان میں نظر آنا چاہیے۔",
    consent: "میں سمجھتا/سمجھتی ہوں کہ یہ تصوراتی درخواست کا عکس ہے، سرکاری رضاکار جمع کرانا نہیں۔",
    submit: "ترجمہ شدہ درخواست تیار کریں",
    languageSkills: "کورین زبان کا مقامی بولنے والا۔ فون، ترجمہ، پناہ گاہ سپورٹ، اور نقشوں میں مدد کر سکتا/سکتی ہے۔",
    availabilityValue: "ہفتے کے دن شام 6 بجے کے بعد اور اختتام ہفتہ دستیاب۔ الرٹس کے دوران ریموٹ مدد کر سکتا/سکتی ہے۔"
  },
  it: {
    back: "Console combinata",
    eyebrow: "Concetto di candidatura volontario",
    title: "Candidati nella lingua che usi meglio",
    languageLabel: "Lingua",
    noticeTitle: "Solo concetto",
    noticeBody: "Questa pagina modella un percorso Red Cross per volontari con la lingua come primo passo. Non e un invio ufficiale.",
    personal: "Informazioni personali",
    fullName: "Nome completo",
    preferredName: "Nome preferito",
    email: "Email",
    phone: "Cellulare",
    zip: "CAP",
    age: "Ho almeno 18 anni",
    yes: "Si",
    no: "No",
    skillsHeading: "Competenze, lingua e disponibilita",
    languages: "Lingue che posso usare per aiutare",
    interests: "Interessi di volontariato",
    disaster: "Risposta ai disastri e supporto alla comunita",
    blood: "Ambasciatore dei donatori di sangue",
    remote: "Supporto remoto o virtuale",
    languageAccess: "Accesso linguistico e interpretariato",
    availability: "Disponibilita",
    supportHeading: "Supporto",
    supportBody: "Se il candidato ha bisogno di aiuto, il percorso ufficiale di supporto ai volontari deve restare visibile nella lingua selezionata.",
    consent: "Capisco che questo e un modello concettuale e non una candidatura ufficiale da volontario.",
    submit: "Prepara la candidatura tradotta",
    languageSkills: "Madrelingua coreano. Puo aiutare con telefoni, traduzione, supporto ai rifugi e mappe.",
    availabilityValue: "Disponibile nei giorni feriali dopo le 18 e nei fine settimana. Puo aiutare da remoto durante gli avvisi."
  },
  pl: {
    back: "Połączona konsola",
    eyebrow: "Koncepcja zgłoszenia wolontariusza",
    title: "Zgłoś się w języku, którego używasz najlepiej",
    languageLabel: "Język",
    noticeTitle: "Tylko koncepcja",
    noticeBody: "Ta strona modeluje zgłoszenie wolontariusza Red Cross, w którym język jest wybierany jako pierwszy. To nie jest oficjalne zgłoszenie.",
    personal: "Informacje osobiste",
    fullName: "Pełne imię i nazwisko",
    preferredName: "Preferowane imię",
    email: "Email",
    phone: "Telefon komórkowy",
    zip: "Kod ZIP",
    age: "Mam 18 lat lub więcej",
    yes: "Tak",
    no: "Nie",
    skillsHeading: "Umiejętności, język i dostępność",
    languages: "Języki, których mogę używać do pomocy",
    interests: "Zainteresowania wolontariackie",
    disaster: "Reagowanie na katastrofy i wsparcie społeczności",
    blood: "Ambasador dawstwa krwi",
    remote: "Wsparcie zdalne lub wirtualne",
    languageAccess: "Dostęp językowy i tłumaczenie ustne",
    availability: "Dostępność",
    supportHeading: "Wsparcie",
    supportBody: "Jeśli kandydat potrzebuje pomocy, oficjalna ścieżka wsparcia wolontariuszy powinna być widoczna w wybranym języku.",
    consent: "Rozumiem, że jest to koncepcyjna kopia formularza, a nie oficjalne zgłoszenie wolontariusza.",
    submit: "Przygotuj przetłumaczone zgłoszenie",
    languageSkills: "Native speaker języka koreańskiego. Może pomagać telefonicznie, w tłumaczeniu, wsparciu schronisk i mapach.",
    availabilityValue: "Dostępny w dni powszednie po 18:00 i w weekendy. Może pomagać zdalnie podczas alertów."
  },
  bn: {
    back: "সমন্বিত কনসোল",
    eyebrow: "স্বেচ্ছাসেবক আবেদন ধারণা",
    title: "আপনি যে ভাষা সবচেয়ে ভালো ব্যবহার করেন তাতে আবেদন করুন",
    languageLabel: "ভাষা",
    noticeTitle: "শুধু ধারণা",
    noticeBody: "এই পৃষ্ঠা ভাষা-প্রথম Red Cross স্বেচ্ছাসেবক আবেদন প্রবাহের একটি মডেল। এটি কোনো সরকারি জমা নয়।",
    personal: "ব্যক্তিগত তথ্য",
    fullName: "পূর্ণ নাম",
    preferredName: "পছন্দের নাম",
    email: "ইমেল",
    phone: "মোবাইল ফোন",
    zip: "ZIP কোড",
    age: "আমার বয়স ১৮ বা তার বেশি",
    yes: "হ্যাঁ",
    no: "না",
    skillsHeading: "দক্ষতা, ভাষা এবং প্রাপ্যতা",
    languages: "যে ভাষাগুলো দিয়ে আমি সাহায্য করতে পারি",
    interests: "স্বেচ্ছাসেবার আগ্রহ",
    disaster: "দুর্যোগ প্রতিক্রিয়া এবং কমিউনিটি সহায়তা",
    blood: "রক্তদাতা দূত",
    remote: "দূরবর্তী বা ভার্চুয়াল সহায়তা",
    languageAccess: "ভাষা প্রবেশাধিকার এবং দোভাষী সহায়তা",
    availability: "প্রাপ্যতা",
    supportHeading: "সহায়তা",
    supportBody: "আবেদনকারীর সাহায্য দরকার হলে, নির্বাচিত ভাষায় সরকারি স্বেচ্ছাসেবক সহায়তার পথ দৃশ্যমান থাকা উচিত।",
    consent: "আমি বুঝি এটি একটি ধারণামূলক আবেদন মিরর, সরকারি স্বেচ্ছাসেবক জমা নয়।",
    submit: "অনূদিত আবেদন প্রস্তুত করুন",
    languageSkills: "কোরিয়ান ভাষার স্থানীয় বক্তা। ফোন, অনুবাদ, আশ্রয় সহায়তা এবং মানচিত্রে সাহায্য করতে পারেন।",
    availabilityValue: "সপ্তাহের দিন সন্ধ্যা ৬টার পরে এবং সপ্তাহান্তে প্রাপ্য। সতর্কতার সময় দূর থেকে সহায়তা করতে পারেন।"
  },
  gu: {
    back: "સંયુક્ત કન્સોલ",
    eyebrow: "સ્વયંસેવક અરજી સંકલ્પના",
    title: "તમે જે ભાષા શ્રેષ્ઠ રીતે વાપરો છો તેમાં અરજી કરો",
    languageLabel: "ભાષા",
    noticeTitle: "માત્ર સંકલ્પના",
    noticeBody: "આ પેજ ભાષા-પ્રથમ Red Cross સ્વયંસેવક અરજી પ્રવાહનું મોડલ બતાવે છે. આ સત્તાવાર સબમિશન નથી.",
    personal: "વ્યક્તિગત માહિતી",
    fullName: "પૂર્ણ નામ",
    preferredName: "પસંદગીનું નામ",
    email: "ઇમેઇલ",
    phone: "મોબાઇલ ફોન",
    zip: "ZIP કોડ",
    age: "હું 18 વર્ષ અથવા વધુ ઉંમરનો છું",
    yes: "હા",
    no: "ના",
    skillsHeading: "કૌશલ્ય, ભાષા અને ઉપલબ્ધતા",
    languages: "મદદ માટે હું વાપરી શકું તેવી ભાષાઓ",
    interests: "સ્વયંસેવક રસ",
    disaster: "આપત્તિ પ્રતિસાદ અને સમુદાય સહાય",
    blood: "રક્તદાતા એમ્બેસેડર",
    remote: "દૂરસ્થ અથવા વર્ચ્યુઅલ સહાય",
    languageAccess: "ભાષા પ્રવેશ અને અર્થઘટન",
    availability: "ઉપલબ્ધતા",
    supportHeading: "સહાય",
    supportBody: "જો અરજદારને મદદ જોઈએ, તો સત્તાવાર સ્વયંસેવક સહાય માર્ગ પસંદ કરેલી ભાષામાં દેખાતો રહેવું જોઈએ.",
    consent: "હું સમજું છું કે આ સંકલ્પનાત્મક અરજી મિરર છે, સત્તાવાર સ્વયંસેવક સબમિશન નથી.",
    submit: "અનુવાદિત અરજી તૈયાર કરો",
    languageSkills: "કોરિયન મૂળ વક્તા. ફોન, અનુવાદ, આશ્રય સહાય અને નકશામાં મદદ કરી શકે છે.",
    availabilityValue: "વિકડેઝે સાંજે 6 પછી અને વીકએન્ડમાં ઉપલબ્ધ. એલર્ટ દરમિયાન દૂરસ્થ મદદ કરી શકે છે."
  },
  ja: {
    back: "統合コンソール",
    eyebrow: "ボランティア申請コンセプト",
    title: "最も使いやすい言語で申請してください",
    languageLabel: "言語",
    noticeTitle: "コンセプトのみ",
    noticeBody: "このページは、言語を最初に選ぶRed Crossボランティア申請フローのモデルです。正式な提出ではありません。",
    personal: "個人情報",
    fullName: "氏名",
    preferredName: "希望する名前",
    email: "メール",
    phone: "携帯電話",
    zip: "郵便番号",
    age: "18歳以上です",
    yes: "はい",
    no: "いいえ",
    skillsHeading: "スキル、言語、対応可能時間",
    languages: "支援に使える言語",
    interests: "ボランティアの関心分野",
    disaster: "災害対応と地域支援",
    blood: "献血ドナーアンバサダー",
    remote: "リモートまたはオンライン支援",
    languageAccess: "言語アクセスと通訳",
    availability: "対応可能時間",
    supportHeading: "サポート",
    supportBody: "申請者が支援を必要とする場合、公式のボランティア支援窓口が選択した言語で表示される必要があります。",
    consent: "これはコンセプト用の申請ミラーであり、正式なボランティア申請ではないことを理解しています。",
    submit: "翻訳済み申請を準備",
    languageSkills: "韓国語のネイティブスピーカー。電話、翻訳、避難所支援、地図業務を支援できます。",
    availabilityValue: "平日午後6時以降と週末に対応可能。警報時にはリモート支援が可能です。"
  },
  fa: {
    back: "کنسول یکپارچه",
    eyebrow: "مفهوم درخواست داوطلب",
    title: "با زبانی که بهتر استفاده می‌کنید درخواست دهید",
    languageLabel: "زبان",
    noticeTitle: "فقط نمونه مفهومی",
    noticeBody: "این صفحه یک جریان درخواست داوطلب Red Cross را نشان می‌دهد که زبان را در ابتدا انتخاب می‌کند. این ارسال رسمی نیست.",
    personal: "اطلاعات شخصی",
    fullName: "نام کامل",
    preferredName: "نام ترجیحی",
    email: "ایمیل",
    phone: "تلفن همراه",
    zip: "کد پستی",
    age: "من ۱۸ سال یا بیشتر دارم",
    yes: "بله",
    no: "خیر",
    skillsHeading: "مهارت‌ها، زبان و زمان‌های در دسترس",
    languages: "زبان‌هایی که می‌توانم برای کمک استفاده کنم",
    interests: "علاقه‌مندی‌های داوطلبی",
    disaster: "پاسخ به بحران و پشتیبانی جامعه",
    blood: "سفیر اهداکنندگان خون",
    remote: "پشتیبانی از راه دور یا مجازی",
    languageAccess: "دسترسی زبانی و ترجمه شفاهی",
    availability: "دسترس‌پذیری",
    supportHeading: "پشتیبانی",
    supportBody: "اگر متقاضی به کمک نیاز دارد، مسیر رسمی پشتیبانی داوطلبان باید در زبان انتخاب‌شده قابل مشاهده باشد.",
    consent: "می‌دانم که این یک نمونه مفهومی درخواست است و ارسال رسمی داوطلبی نیست.",
    submit: "آماده‌سازی درخواست ترجمه‌شده",
    languageSkills: "گویشور بومی کره‌ای. می‌تواند در تماس تلفنی، ترجمه، پشتیبانی پناهگاه و نقشه‌ها کمک کند.",
    availabilityValue: "روزهای کاری پس از ساعت ۶ عصر و آخر هفته‌ها در دسترس است. هنگام هشدارها می‌تواند از راه دور کمک کند."
  }
};

const recordHandoffCopy = {
  en: {
    recordTitle: "English record for Red Cross systems",
    recordBody: "The applicant completes the form in their preferred language. The staged packet creates an English version for Red Cross records and keeps the original-language answers attached for review.",
    stageToast: "English record staged for Red Cross review; original-language answers remain attached."
  },
  ko: {
    recordTitle: "적십자 시스템용 영어 기록",
    recordBody: "신청자는 선호하는 언어로 양식을 작성합니다. 준비된 패킷은 적십자 기록용 영어 버전을 만들고, 검토를 위해 원문 답변을 함께 보관합니다.",
    stageToast: "적십자 검토용 영어 기록이 준비되었고 원문 답변도 함께 보관됩니다."
  },
  es: {
    recordTitle: "Registro en inglés para los sistemas de Red Cross",
    recordBody: "La persona completa el formulario en su idioma preferido. El paquete preparado crea una versión en inglés para los registros de Red Cross y conserva las respuestas originales para revisión.",
    stageToast: "Registro en inglés preparado para revisión de Red Cross; las respuestas originales siguen adjuntas."
  },
  zh: {
    recordTitle: "供 Red Cross 系统使用的英文记录",
    recordBody: "申请人使用自己偏好的语言填写表格。准备好的资料包会生成供 Red Cross 记录使用的英文版本，并保留原语言答案以便审核。",
    stageToast: "已准备供 Red Cross 审核的英文记录；原语言答案仍随附。"
  },
  tl: {
    recordTitle: "English record para sa mga sistema ng Red Cross",
    recordBody: "Pinupunan ng aplikante ang form sa wikang pinakakomportable sa kanya. Gumagawa ang inihandang packet ng English version para sa Red Cross records at nakakabit pa rin ang orihinal na sagot para sa review.",
    stageToast: "Naihanda ang English record para sa Red Cross review; nakakabit pa rin ang orihinal na sagot."
  },
  vi: {
    recordTitle: "Hồ sơ tiếng Anh cho hệ thống Red Cross",
    recordBody: "Người nộp đơn điền biểu mẫu bằng ngôn ngữ họ muốn dùng. Gói hồ sơ được chuẩn bị sẽ tạo bản tiếng Anh cho hồ sơ Red Cross và giữ kèm câu trả lời gốc để xem xét.",
    stageToast: "Hồ sơ tiếng Anh đã được chuẩn bị để Red Cross xem xét; câu trả lời gốc vẫn được đính kèm."
  },
  ar: {
    recordTitle: "سجل باللغة الإنجليزية لأنظمة Red Cross",
    recordBody: "يملأ مقدم الطلب النموذج بلغته المفضلة. تنشئ الحزمة المجهزة نسخة باللغة الإنجليزية لسجلات Red Cross وتبقي الإجابات باللغة الأصلية مرفقة للمراجعة.",
    stageToast: "تم تجهيز سجل إنجليزي لمراجعة Red Cross؛ وتظل الإجابات الأصلية مرفقة."
  },
  fr: {
    recordTitle: "Dossier en anglais pour les systemes Red Cross",
    recordBody: "La personne remplit le formulaire dans la langue qu'elle prefere. Le dossier prepare cree une version anglaise pour les dossiers Red Cross et conserve les reponses originales pour revision.",
    stageToast: "Dossier anglais prepare pour la revision Red Cross; les reponses originales restent jointes."
  },
  pt: {
    recordTitle: "Registro em inglês para os sistemas Red Cross",
    recordBody: "A pessoa preenche o formulario no idioma que prefere. O pacote preparado cria uma versao em ingles para os registros Red Cross e mantem as respostas originais anexadas para revisao.",
    stageToast: "Registro em ingles preparado para revisao Red Cross; as respostas originais permanecem anexadas."
  },
  hi: {
    recordTitle: "Red Cross सिस्टम के लिए अंग्रेज़ी रिकॉर्ड",
    recordBody: "आवेदक अपनी पसंदीदा भाषा में फॉर्म भरता है। तैयार पैकेट Red Cross रिकॉर्ड के लिए अंग्रेज़ी संस्करण बनाता है और समीक्षा के लिए मूल भाषा के उत्तर साथ रखता है।",
    stageToast: "Red Cross समीक्षा के लिए अंग्रेज़ी रिकॉर्ड तैयार है; मूल भाषा के उत्तर साथ संलग्न हैं."
  },
  ht: {
    recordTitle: "Dosye angle pou sistèm Red Cross",
    recordBody: "Aplikan an ranpli fòm nan nan lang li prefere a. Pake ki prepare a kreye yon vèsyon angle pou dosye Red Cross epi kenbe repons nan lang orijinal la atache pou revizyon.",
    stageToast: "Dosye angle prepare pou revizyon Red Cross; repons lang orijinal yo rete atache."
  },
  ru: {
    recordTitle: "Английская запись для систем Red Cross",
    recordBody: "Заявитель заполняет форму на предпочитаемом языке. Подготовленный пакет создает английскую версию для записей Red Cross и сохраняет ответы на исходном языке для проверки.",
    stageToast: "Английская запись подготовлена для проверки Red Cross; ответы на исходном языке остаются приложенными."
  },
  de: {
    recordTitle: "Englischer Datensatz fur Red Cross Systeme",
    recordBody: "Die antragstellende Person fullt das Formular in ihrer bevorzugten Sprache aus. Das vorbereitete Paket erstellt eine englische Version fur Red Cross Unterlagen und behalt die Originalantworten zur Prufung bei.",
    stageToast: "Englischer Datensatz fur Red Cross Prufung vorbereitet; Originalantworten bleiben angehangt."
  },
  te: {
    recordTitle: "Red Cross వ్యవస్థల కోసం ఇంగ్లీష్ రికార్డు",
    recordBody: "దరఖాస్తుదారు తనకు ఇష్టమైన భాషలో ఫారమ్ పూర్తి చేస్తారు. సిద్ధం చేసిన ప్యాకెట్ Red Cross రికార్డుల కోసం ఇంగ్లీష్ వెర్షన్ సృష్టిస్తుంది మరియు సమీక్ష కోసం అసలు భాష సమాధానాలను జతచేస్తుంది.",
    stageToast: "Red Cross సమీక్ష కోసం ఇంగ్లీష్ రికార్డు సిద్ధమైంది; అసలు భాష సమాధానాలు జతచేయబడ్డాయి."
  },
  ur: {
    recordTitle: "Red Cross نظاموں کے لیے انگریزی ریکارڈ",
    recordBody: "درخواست دہندہ فارم اپنی پسندیدہ زبان میں مکمل کرتا ہے۔ تیار کردہ پیکٹ Red Cross ریکارڈز کے لیے انگریزی ورژن بناتا ہے اور جائزے کے لیے اصل زبان کے جوابات ساتھ رکھتا ہے۔",
    stageToast: "Red Cross جائزے کے لیے انگریزی ریکارڈ تیار ہے؛ اصل زبان کے جوابات منسلک رہتے ہیں۔"
  },
  it: {
    recordTitle: "Record in inglese per i sistemi Red Cross",
    recordBody: "La persona compila il modulo nella lingua che preferisce. Il pacchetto preparato crea una versione in inglese per gli archivi Red Cross e conserva le risposte originali per la revisione.",
    stageToast: "Record in inglese preparato per la revisione Red Cross; le risposte originali restano allegate."
  },
  pl: {
    recordTitle: "Angielski rekord dla systemów Red Cross",
    recordBody: "Osoba składająca wniosek wypełnia formularz w preferowanym języku. Przygotowany pakiet tworzy wersję angielską do dokumentacji Red Cross i zachowuje oryginalne odpowiedzi do przeglądu.",
    stageToast: "Angielski rekord przygotowany do przeglądu Red Cross; oryginalne odpowiedzi pozostają załączone."
  },
  bn: {
    recordTitle: "Red Cross সিস্টেমের জন্য ইংরেজি রেকর্ড",
    recordBody: "আবেদনকারী নিজের পছন্দের ভাষায় ফর্ম পূরণ করেন। প্রস্তুত প্যাকেটটি Red Cross রেকর্ডের জন্য একটি ইংরেজি সংস্করণ তৈরি করে এবং পর্যালোচনার জন্য মূল ভাষার উত্তর সংযুক্ত রাখে।",
    stageToast: "Red Cross পর্যালোচনার জন্য ইংরেজি রেকর্ড প্রস্তুত; মূল ভাষার উত্তর সংযুক্ত আছে।"
  },
  gu: {
    recordTitle: "Red Cross સિસ્ટમ માટે અંગ્રેજી રેકોર્ડ",
    recordBody: "અરજદાર પોતાની પસંદગીની ભાષામાં ફોર્મ પૂર્ણ કરે છે. તૈયાર પેકેટ Red Cross રેકોર્ડ માટે અંગ્રેજી આવૃત્તિ બનાવે છે અને સમીક્ષા માટે મૂળ ભાષાના જવાબો જોડેલા રાખે છે.",
    stageToast: "Red Cross સમીક્ષા માટે અંગ્રેજી રેકોર્ડ તૈયાર છે; મૂળ ભાષાના જવાબો જોડેલા છે."
  },
  ja: {
    recordTitle: "Red Crossシステム用の英語記録",
    recordBody: "申請者は希望する言語でフォームに入力します。準備されたパケットはRed Cross記録用の英語版を作成し、確認用に元の言語の回答も添付したままにします。",
    stageToast: "Red Cross確認用の英語記録を準備しました。元の言語の回答も添付されています。"
  },
  fa: {
    recordTitle: "رکورد انگلیسی برای سامانه‌های Red Cross",
    recordBody: "متقاضی فرم را به زبان دلخواه خود تکمیل می‌کند. بسته آماده‌شده نسخه انگلیسی را برای سوابق Red Cross ایجاد می‌کند و پاسخ‌های زبان اصلی را برای بازبینی پیوست نگه می‌دارد.",
    stageToast: "رکورد انگلیسی برای بازبینی Red Cross آماده شد؛ پاسخ‌های زبان اصلی همچنان پیوست هستند."
  }
};

Object.entries(recordHandoffCopy).forEach(([language, phrases]) => {
  Object.assign(copy[language], phrases);
});

const params = new URLSearchParams(window.location.search);

if (params.get("embed") === "phone") {
  document.body.classList.add("intake-embed");
}

const languageSelect = document.querySelector("#language");
const toast = document.querySelector("#toast");

if (params.get("lang") && copy[params.get("lang")]) {
  languageSelect.value = params.get("lang");
}

function currentCopy() {
  return { ...copy.en, ...(copy[languageSelect.value] || {}) };
}

function updateLanguage() {
  const data = currentCopy();
  document.documentElement.lang = languageSelect.value;
  document.documentElement.dir = ["ar", "ur", "fa"].includes(languageSelect.value) ? "rtl" : "ltr";
  document.querySelectorAll("[data-text]").forEach((node) => {
    const key = node.dataset.text;
    if (data[key]) node.textContent = data[key];
  });
  document.querySelector("#languageSkills").value = data.languageSkills;
  document.querySelector("#availability").value = data.availabilityValue;
}

function showToast(message) {
  toast.textContent = message;
  toast.classList.add("visible");
  window.setTimeout(() => toast.classList.remove("visible"), 2200);
}

languageSelect.addEventListener("change", updateLanguage);
document.querySelector("#stageApplication").addEventListener("click", () => {
  showToast(currentCopy().stageToast);
});

updateLanguage();
